### ISSUE TITLE
cv2.error: OpenCV(4.7.0-dev) error: (-5:Bad argument) in function 'circle' > Overload resolution failed: >  - Can't parse 'center'. Sequence item with index 0 has a wrong type

### ISSUE THREAD

**Issue by elysia-best** [zenxan/IPM_transform#1]
使用提供的测试图片时报错：
```
Traceback (most recent call last):
  File "e:\Projects\IPM_transform\python\ipm_tran.py", line 59, in <module>
    multi_transform(img, pts1)
  File "e:\Projects\IPM_transform\python\ipm_tran.py", line 29, in multi_transform
    cv2.circle(img, (pts1[i][0], pts1[i][1]), 6, (0, 0, 255), cv2.FILLED)
cv2.error: OpenCV(4.7.0-dev) :-1: error: (-5:Bad argument) in function 'circle'
> Overload resolution failed:
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
>  - Can't parse 'center'. Sequence item with index 0 has a wrong type
```

使用的环境如下：
Windows10
Python 3.10.11
OpenCV 4.7.0

**Comment by zenxan** [comment]
It may be that your pts1 variable uses float type, which should be of type int
